name: Run Python Script

on: [push]  # Runs when code is pushed

jobs:
  build:
    runs-on: ubuntu-latest  # Uses a Linux machine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python main.py  # Change this to your main Python file
